name: deploy to render

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: srv-cluuuf6g1b2c73cc34e0?key=IXJD1pan_Kk
          api-key: rnd_yNQBSK82Kej1839OyMdvNvGXxq2P
          wait-for-success: true
